version: '3.8'
services:
  mongo:
    image: mongo
    ports: 
      - "27017:27017"
    
  http:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.http
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.web
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  website:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.website
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo

