name: Deploy the backend
on:
    push:
        branches:[ prod ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
                uses: actions/checkout@v2

            - name: Docker Login
                uses: docker/login-action@v2
                with:
                    username:${{secrets.DOCKERHUB_USERNAME}}
                    password:${{secrets.DOCKERHUB_PASSWORD}}