name: Deploy the Http
on:
    push:
        branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Docker Login
              uses: docker/login-action@v2
              with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: ./
                file: ./docker/Dockerfile.http
                push: true
                tags: avishmadaan/tweetly-http:${{github.sha}}

            - name: executing remote ssh commands
              uses: appleboy/ssh-action@v1.2.0
              with: 
                  host: 134.209.156.16
                  username: root
                  key: ${{secrets.SSH_PRIVATE_KEY_DO}}
                  port: 22
                  script: |
                      docker stop http
                      docker run --name http --env-file .env  -d -p 3001:30001 avishmadaan/tweetly-website:${{github.sha}}